#!/bin/bash

trap cleanup SIGINT SIGTERM ERR

cleanup(){
  if [ -n $VIRTUAL_ENV ]; then
    deactivate 2>/dev/null
  fi
}

COMMAND=$1

if [ -n $2 ]; then
  TIME=$2
else
  TIME=120
fi

MEM_USAGE=$(which mem_usage)

PYTHON_CMD=$(which python3)

PYTHON_REQUIREMENTS=("matplotlib")

if [ -z "$PYTHON_CMD" ]; then
    PYTHON_CMD=$(which python)
fi

activate_venv(){
  if ! [ -d venv ]; then
    echo "Installing virtual environment"
    $PYTHON_CMD -m venv venv
  fi

  source venv/bin/activate

  if [ -z "$VIRTUAL_ENV" ]; then
    echo "Virtual environment not activated."
    cleanup 1
  fi

# Use python3 from venv
  python3 -m ensurepip --upgrade
  for r in "${PYTHON_REQUIREMENTS[@]}"; do
    pip install $r
  done
}

echo "Measuring memory usage for ${TIME} seconds."
$COMMAND &
pid=$!
$MEM_USAGE &
pid_mem=$!
sleep $TIME

kill $pid_mem
kill $pid

activate_venv

plot_measurements.py mem.csv

cleanup 0
